In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import tree

In [12]:
data=pd.read_csv("Datasets/pacific.csv")
data

,ID,Name,Date,Time,Event,Status,Latitude,Longitude,Maximum Wind,Minimum Pressure,...,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,EP011949,UNNAMED,19490611,0,,TS,20.2N,106.3W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,EP011949,UNNAMED,19490611,600,,TS,20.2N,106.4W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,EP011949,UNNAMED,19490611,1200,,TS,20.2N,106.7W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,EP011949,UNNAMED,19490611,1800,,TS,20.3N,107.7W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,EP011949,UNNAMED,19490612,0,,TS,20.4N,108.6W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26132,EP222015,SANDRA,20151128,1200,,LO,21.7N,109.0W,35,1002,...,0,0,0,0,0,0,0,0,0,0
26133,EP222015,SANDRA,20151128,1800,,LO,22.4N,108.7W,30,1007,...,0,0,0,0,0,0,0,0,0,0
26134,EP222015,SANDRA,20151129,0,,LO,23.1N,108.3W,30,1008,...,0,0,0,0,0,0,0,0,0,0
26135,EP222015,SANDRA,20151129,600,,LO,23.5N,107.9W,25,1009,...,0,0,0,0,0,0,0,0,0,0
26136,EP222015,SANDRA,20151129,1200,,LO,24.2N,107.7W,20,1010,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#2.Data Wrangling

In [13]:
pred_columns=data[:]

In [15]:
pred_columns.drop(['ID','Name','Date','Time','Event','Status','Latitude','Longitude'],inplace=True,axis=1)
pred_columns.head()

C:\Users\azart\AppData\Local\Temp\ipykernel_14572\1406943641.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pred_columns.drop(['ID','Name','Date','Time','Event','Status','Latitude','Longitude'],inplace=True,axis=1)

,Maximum Wind,Minimum Pressure,Low Wind NE,Low Wind SE,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [16]:
#list of input columns
input_columns=list(pred_columns)
input_columns

['Maximum Wind',
 'Minimum Pressure',
 'Low Wind NE',
 'Low Wind SE',
 'Low Wind SW',
 'Low Wind NW',
 'Moderate Wind NE',
 'Moderate Wind SE',
 'Moderate Wind SW',
 'Moderate Wind NW',
 'High Wind NE',
 'High Wind SE',
 'High Wind SW',
 'High Wind NW']

In [18]:
# sns.countplot(data['Status'],label='count')
# plt.show()

In [19]:
#Spliting the data into training and testing 
train,test=train_test_split(data,test_size=0.3)

In [22]:
train_X=train[input_columns]
train_Y=train['Status']

In [23]:
test_X=test[input_columns]
test_Y=test['Status']

In [25]:
#model
model=tree.DecisionTreeClassifier()

In [27]:
#Training the model
model.fit(train_X,train_Y)
predicition=model.predict(test_X)

In [29]:
metrics.accuracy_score(predicition,test_Y)

0.9570262688089773

In [30]:
d=pd.DataFrame({'predicated_value':predicition,'KnownO/P':test_Y})
d

      predicated_value KnownO/P
11768               TS       TS
7350                TS       TS
16503               TS       TS
835                 HU       HU
1828                TD       TD
...                ...      ...
17483               HU       HU
16046               TD       TD
3779                HU       HU
874                 HU       HU
12551               TD       TD

[7842 rows x 2 columns]

In [31]:
tree.export_graphviz(model, out_file='decision_tree.dot', feature_names=input_columns)

In [32]:
from sklearn.datasets import load_iris
from sklearn import tree

In [33]:
clf = tree.DecisionTreeClassifier()
iris = load_iris()

In [35]:
clf = clf.fit(iris.data, iris.target)
tree.export_graphviz(clf)

'digraph Tree {\nnode [shape=box, fontname="helvetica"] ;\nedge [fontname="helvetica"] ;\n0 [label="x[3] <= 0.8\\ngini = 0.667\\nsamples = 150\\nvalue = [50, 50, 50]"] ;\n1 [label="gini = 0.0\\nsamples = 50\\nvalue = [50, 0, 0]"] ;\n0 -> 1 [labeldistance=2.5, labelangle=45, headlabel="True"] ;\n2 [label="x[3] <= 1.75\\ngini = 0.5\\nsamples = 100\\nvalue = [0, 50, 50]"] ;\n0 -> 2 [labeldistance=2.5, labelangle=-45, headlabel="False"] ;\n3 [label="x[2] <= 4.95\\ngini = 0.168\\nsamples = 54\\nvalue = [0, 49, 5]"] ;\n2 -> 3 ;\n4 [label="x[3] <= 1.65\\ngini = 0.041\\nsamples = 48\\nvalue = [0, 47, 1]"] ;\n3 -> 4 ;\n5 [label="gini = 0.0\\nsamples = 47\\nvalue = [0, 47, 0]"] ;\n4 -> 5 ;\n6 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 0, 1]"] ;\n4 -> 6 ;\n7 [label="x[3] <= 1.55\\ngini = 0.444\\nsamples = 6\\nvalue = [0, 2, 4]"] ;\n3 -> 7 ;\n8 [label="gini = 0.0\\nsamples = 3\\nvalue = [0, 0, 3]"] ;\n7 -> 8 ;\n9 [label="x[2] <= 5.45\\ngini = 0.444\\nsamples = 3\\nvalue = [0, 2, 1]"] ;\n7 -> 9 ;\n10 [label="gini = 0.0\\nsamples = 2\\nvalue = [0, 2, 0]"] ;\n9 -> 10 ;\n11 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 0, 1]"] ;\n9 -> 11 ;\n12 [label="x[2] <= 4.85\\ngini = 0.043\\nsamples = 46\\nvalue = [0, 1, 45]"] ;\n2 -> 12 ;\n13 [label="x[0] <= 5.95\\ngini = 0.444\\nsamples = 3\\nvalue = [0, 1, 2]"] ;\n12 -> 13 ;\n14 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1, 0]"] ;\n13 -> 14 ;\n15 [label="gini = 0.0\\nsamples = 2\\nvalue = [0, 0, 2]"] ;\n13 -> 15 ;\n16 [label="gini = 0.0\\nsamples = 43\\nvalue = [0, 0, 43]"] ;\n12 -> 16 ;\n}'

In [ ]:
# paste the binary file O/P in http://www.webgraphviz.com/

In [ ]:
#RandomForest
#Ensemble of many decision trees

In [36]:
from sklearn.ensemble import RandomForestClassifier
#Number of decision tree  in 100
model=RandomForestClassifier(n_estimators=100)
#Training
model.fit(train_X,train_Y)
#Test
predicition=model.predict(test_X)
metrics.accuracy_score(test_Y,predicition)

0.958173935220607